// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVGGggNNGq4zUsulCNx2wsz1CAlg55i4s',
    appId: '1:267515153341:web:ae4e2456bd582f85e6a0d4',
    messagingSenderId: '267515153341',
    projectId: 'dineos-123',
    authDomain: 'dineos-123.firebaseapp.com',
    databaseURL: 'https://dineos-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dineos-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLzdYqvHGV_L2SA1OAOwwe8szc79qPwgc',
    appId: '1:267515153341:android:880e172bc98c845ae6a0d4',
    messagingSenderId: '267515153341',
    projectId: 'dineos-123',
    databaseURL: 'https://dineos-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dineos-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSw325OUHw6MrxAGIdwbWHPyhJRldolc',
    appId: '1:267515153341:ios:e06cfa7bfb3df34fe6a0d4',
    messagingSenderId: '267515153341',
    projectId: 'dineos-123',
    databaseURL: 'https://dineos-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dineos-123.firebasestorage.app',
    iosBundleId: 'com.example.dineosDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsSw325OUHw6MrxAGIdwbWHPyhJRldolc',
    appId: '1:267515153341:ios:e06cfa7bfb3df34fe6a0d4',
    messagingSenderId: '267515153341',
    projectId: 'dineos-123',
    databaseURL: 'https://dineos-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dineos-123.firebasestorage.app',
    iosBundleId: 'com.example.dineosDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVGGggNNGq4zUsulCNx2wsz1CAlg55i4s',
    appId: '1:267515153341:web:fa8fa33e9394242de6a0d4',
    messagingSenderId: '267515153341',
    projectId: 'dineos-123',
    authDomain: 'dineos-123.firebaseapp.com',
    databaseURL: 'https://dineos-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dineos-123.firebasestorage.app',
  );
}
